# Site settings
title: Voor.xyz
email: voor@voor.xyz
url: https://www.voor.xyz
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Software Architect - Full Stack Developer - Techie"
meta_author: Robert Van Voorhees

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: voorxyz

gems:
  - jekyll-bootstrap-sass

# Change to SASS
sass:
    style: compressed

# Footer settings
footer:
  copyright: Robert Van Voorhees
  location: Location
  social: Around the Web
  credits: Disclaimer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rcvoor
  - title: stack-overflow
    url: https://stackoverflow.com/users/3515753/voor
  - title: github
    url: http://github.com/voor
  - title: linkedin
    url: https://www.linkedin.com/in/voors

# Postal address (add as many lines as necessary)
address:
  - line: Maryland, USA

# Credits content
credits: 'This is my personal blog. The views expressed on these pages are mine alone and not those of my employer.'

# Build settings
markdown: kramdown
permalink: pretty
